/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthorRegister: typeof import('./components/organisms/AuthorRegister.vue')['default']
    BaseButton: typeof import('./components/atoms/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/atoms/BaseIcon.vue')['default']
    BaseInputField: typeof import('./components/atoms/BaseInputField.vue')['default']
    BaseLoading: typeof import('./components/atoms/BaseLoading.vue')['default']
    BasePagination: typeof import('./components/atoms/BasePagination.vue')['default']
    BaseToastMessage: typeof import('./components/atoms/BaseToastMessage.vue')['default']
    DefaultFooter: typeof import('./components/organisms/DefaultFooter.vue')['default']
    DefaultHeader: typeof import('./components/organisms/DefaultHeader.vue')['default']
    DefaultList: typeof import('./components/organisms/DefaultList.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    MenuGenre: typeof import('./components/molecules/MenuGenre.vue')['default']
    MenuStory: typeof import('./components/molecules/MenuStory.vue')['default']
    RegisterModal: typeof import('./components/molecules/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
